server:
  port: 8081
  max-http-request-header-size: 10KB
spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      authentication-database: admin
      username: root
      password: mongodb
      database: gateway
  cloud:
    gateway:
        server:
          webflux:
            globalcors:
              corsConfigurations:
                '[/**]':
                  allowedOrigins: http://localhost:3000
                  allowedMethods: "*"
                  allowedHeaders: "*"
                  allowCredentials: true

management:
  endpoint:
    gateway:
      access: UNRESTRICTED
  endpoints:
    web:
      exposure:
        include: "*"

liminallabs:
  gateway:
    session-cookie-name: QUESTMASTER_SESSION
    oauth-callback-url: http://localhost:8081/oauth/callback
    frontend-url: http://localhost:3000
    cookie-domain: localhost
    cookie-same-site: Strict
    cookie-secure: false
    cookie-max-age: 3600
    auth:
      provider-name: keycloak
      keycloak:
        base-url: http://localhost:8080
        base-url-internal: http://localhost:8080
        realm: LiminalLabs
        client-id: questmaster
        client-secret: xKa7P5CGXwoYnSjQrI7g9UUXYP16LXOw