server:
  port: 8080

spring:
  cloud:
    gateway:
        server:
          webflux:
            globalcors:
              corsConfigurations:
                '[/**]':
                  allowedOrigins: ${ALLOWED_ORIGIN}
                  allowedMethods: "*"
                  allowedHeaders: "*"
                  allowCredentials: true