server:
  port: 8081
  max-http-request-header-size: 10KB

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: gateway
    password: gateway
  data:
    mongodb:
      host: localhost
      port: 27018
      authentication-database: admin
      username: root
      password: mongodb
      database: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${HBSITES_GATEWAY_FRONTEND_URL}
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

hbsites:
  gateway:
    session_cookie_name: ${HBSITES_GATEWAY_SESSION_COOKIE_NAME}
    oauth_callback_url: ${HBSITES_GATEWAY_OAUTH_CALLBACK_URL}
    frontend_url: ${HBSITES_GATEWAY_FRONTEND_URL}
    keycloak:
      base_url: ${HBSITES_GATEWAY_KEYCLOAK_BASE_URL}
      realm: ${HBSITES_GATEWAY_KEYCLOAK_REALM}
      client_id: ${HBSITES_GATEWAY_KEYCLOAK_CLIENT_ID}
      client_secret: ${HBSITES_GATEWAY_KEYCLOAK_CLIENT_SECRET}
    amqp:
      queue: ${HBSITES_GATEWAY_AMQP_QUEUE}