server:
  port: 8081
  max-http-request-header-size: 10KB

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: questmaster-gateway
    password: questmaster-gateway
  data:
    mongodb:
      host: localhost
      port: 27018
      authentication-database: admin
      username: root
      password: mongodb
      database: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: http://localhost:3000
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

liminallabs:
  gateway:
    session_cookie_name: QUESTMASTER_SESSION
    oauth_callback_url: http://localhost:8081/oauth/callback
    frontend_url: http://localhost:3000
    keycloak:
      base_url: http://localhost:8080
      base_url_internal: http://localhost:8080
      realm: LiminalLabs
      client_id: questmaster
      client_secret: xKa7P5CGXwoYnSjQrI7g9UUXYP16LXOw
    amqp:
      queue: questmaster-update-paths